database:
- name: Recipeapp
    databaseName: mysite
    user: Recipeapp

services:
 - type: web
   name: Recipeapp
  runtime: ruby
     buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
   envVars:
      - key: DATABASE_URL
        fromDatabase:
          name:  Recipeapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false